FROM ubuntu:focal
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# 패키지 설치 및 의존성 업데이트
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    wget \
    gnupg \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# 크롬 설치
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update && apt-get install -y google-chrome-stable \
    && rm -rf /var/lib/apt/lists/*

# 앱 소스 코드 복사
COPY . /app

# 필요한 파이썬 패키지 설치
RUN pip3 install -r requirements.txt

# 컨테이너 실행 시 실행될 명령
CMD ["python3", "app.py"]
